In [1]:
from datascience import *
import numpy as np
import warnings
warnings.filterwarnings("ignore")

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
plots.rcParams["patch.force_edgecolor"] = True

### Last Week's Survey

In [55]:
survey = Table.read_table('class_survey.csv')
survey

Are you a Barnard student or Columbia student? | What is your major?               | Are you left-handed or right-handed? | Roughly how many hours of sleep do you get on a weeknight during the semester? | Roughly how many hours of sleep do you get on a weekend during the semester? | On any given day, roughly how many browser tabs do you have open? | Did you answer honestly to all of the questions?
Barnard                                        | Economics or Economics-Statistics | Right-handed                         | 7.5                                                                            | 9                                                                            | 20                                                                | Yes
Barnard                                        | Cognitive Science                 | Right-handed                         | 7.5                                                                            | 8                                                                            | 10                                                                | Yes
Barnard                                        | Economics or Economics-Statistics | Left-handed                          | 7                                                                              | 8                                                                            | 47                                                                | No
Barnard                                        | Economics or Economics-Statistics | Left-handed                          | 7                                                                              | 8                                                                            | 15                                                                | Yes
Barnard                                        | Cognitive Science                 | Right-handed                         | 8                                                                              | 9                                                                            | 10                                                                | Yes
Barnard                                        | Cognitive Science                 | Right-handed                         | 7                                                                              | 6                                                                            | 8                                                                 | Yes
Barnard                                        | Undeclared                        | Right-handed                         | 7                                                                              | 9                                                                            | 15                                                                | Yes
Barnard                                        | Dance                             | Ambidextrous                         | 7                                                                              | 11                                                                           | 999                                                               | No
Barnard                                        | Economics or Economics-Statistics | Right-handed                         | 8                                                                              | 8                                                                            | 30                                                                | Yes
Barnard                                        | Economics or Economics-Statistics | Ambidextrous                         | 8                                                                              | 10                                                                           | 12                                                                | Yes
... (25 rows omitted)

In [59]:
survey_relabeled = survey.relabeled('What is your major?', 'Major').relabeled('Did you answer honestly to all of the questions?', 'Honesty').relabeled('On any given day, roughly how many browser tabs do you have open?', 'Browser Tabs')
survey_relabeled.show(3)

In [63]:
survey_relabeled.select('Major', 'Honesty', 'Browser Tabs').group('Honesty', np.average)

Honesty | Major average | Browser Tabs average
No      |               | 348.667
Yes     |               | 66.1379

In [66]:
survey_relabeled.select('Major', 'Honesty', 'Browser Tabs').pivot('Honesty', 'Major', 'Browser Tabs', np.average)

Major                             | No      | Yes
Applied Mathematics               | 16      | 40
Cognitive Science                 | 0       | 12.1667
Dance                             | 999     | 260
Economics or Economics-Statistics | 353.667 | 97.6667
Psychology                        | 0       | 20
Undeclared                        | 0       | 13.2857

In [67]:
survey_relabeled.select('Major', 'Honesty', 'Browser Tabs').pivot('Honesty', 'Major')

Major                             | No   | Yes
Applied Mathematics               | 2    | 1
Cognitive Science                 | 0    | 6
Dance                             | 1    | 2
Economics or Economics-Statistics | 3    | 12
Psychology                        | 0    | 1
Undeclared                        | 0    | 7

### Create functions

In [9]:
def age(year):
    "Takes as input the birth year and computes their age as of 2026"
    return 2026 - year

In [32]:
age(2000)

26

In [38]:
def age_as_of(birth_year, current_year=2026):
    "Takes in a two years and computes the age as of the second year"
    return current_year - birth_year

In [37]:
age_as_of(2000, current_year = 2090)

90

In [7]:
age_as_of(2000, 2015)

15

In [5]:
age(2000)

26

In [12]:
age_as_of?

Signature: age_as_of(birth_year, current_year)
Docstring: Takes in a two years and computes the age as of the second year
File:      /tmp/ipykernel_204/3587685706.py
Type:      function

##### **Task:** Create a function called `name_and_age()` that:
- takes a person's `name` and `year` of birth (two arguments). 
- produces a sentence that states how old they are (such as, "Jeremy is 26 years old").

In [19]:
jeremy = "Jeremy"
jeremy_age = 26
jeremy + ' is ' + str(jeremy_age) + ' years old'

'Jeremy is 26 years old'

In [23]:
str(jeremy_age)

'26'

In [17]:
'hello'+ ' ' + 'there'

'hello there'

In [24]:
def name_and_age(name,year):
    return name + ' is ' + str(age(year)) + ' years old'

In [25]:
name_and_age('Jeremy', 2000)

'Jeremy is 26 years old'

In [26]:
name_and_age('Ruby', 2011)

'Ruby is 15 years old'

### Use functions on table columns with `apply`

In [39]:
fam = Table().with_columns(
    'First Name', make_array('Jeremy', 'Olivia', 'Data 8'),
    'Birth Year', make_array(1999, 2005, 2015)
)
fam

First Name | Birth Year
Jeremy     | 1999
Olivia     | 2005
Data 8     | 2015

In [40]:
fam.apply(age, 'Birth Year')

array([27, 21, 11])

In [41]:
fam.apply(name_and_age, 'First Name', 'Birth Year')

array(['Jeremy is 27 years old', 'Olivia is 21 years old',
       'Data 8 is 11 years old'],
      dtype='<U22')

In [42]:
fam.with_columns('Statement', fam.apply(name_and_age, 'First Name', 'Birth Year'))

First Name | Birth Year | Statement
Jeremy     | 1999       | Jeremy is 27 years old
Olivia     | 2005       | Olivia is 21 years old
Data 8     | 2015       | Data 8 is 11 years old

Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length $h$ satisfies:

$$ h^2 = x^2 + y^2 \qquad \text{which implies}\qquad \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $$

Write a function `hypotenuse` that takes in right angle sides with length `x` and `y` and calculates the hypotenuse.

In [ ]:
def hypotenuse(x, y):
    """finds the hypotenuse of a right triangle with right-angle sides of length x and y"""
    ...
    return hypot

### One-column groups

In [43]:
cones = Table.read_table('cones.csv')
cones_without_color = cones.drop('Color')

In [46]:
cones_without_color.group('Flavor')

Flavor     | count
bubblegum  | 1
chocolate  | 3
strawberry | 2

In [47]:
cones_without_color.group('Flavor', np.average)

Flavor     | Price average
bubblegum  | 4.75
chocolate  | 5.08333
strawberry | 4.4

In [48]:
cones_without_color.group('Flavor', sum)

Flavor     | Price sum
bubblegum  | 4.75
chocolate  | 15.25
strawberry | 8.8

In [51]:
cones.group(['Flavor', 'Color'], max)

Flavor     | Color       | Price max
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
strawberry | pink        | 5.25

In [65]:
cones.pivot('Flavor', 'Color', 'Price', np.average)

Color       | bubblegum | chocolate | strawberry
dark brown  | 0         | 5.25      | 0
light brown | 0         | 4.75      | 0
pink        | 4.75      | 0         | 4.4

_______

### Know when to use grouping vs. pivoting!

In [68]:
# https://corgis-edu.github.io/corgis/csv/skyscrapers/
skyscrapers = Table.read_table('skyscrapers.csv')
skyscrapers.show(6)

How can I find the tallest building per material for each city?

In [70]:
skyscrapers.select('city', 'material', 'height').group(['city', 'material'], max)

city      | material        | height max
Atlanta   | concrete        | 264.25
Atlanta   | mixed/composite | 311.8
Atlanta   | steel           | 169.47
Austin    | concrete        | 208.15
Austin    | steel           | 93.6
Baltimore | concrete        | 161.24
Baltimore | steel           | 155.15
Boston    | concrete        | 121.92
Boston    | mixed/composite | 139
Boston    | steel           | 240.79
... (81 rows omitted)

In [72]:
skyscrapers.pivot('material','city',  'height', max)

city       | concrete | mixed/composite | steel
Atlanta    | 264.25   | 311.8           | 169.47
Austin     | 208.15   | 0               | 93.6
Baltimore  | 161.24   | 0               | 155.15
Boston     | 121.92   | 139             | 240.79
Charlotte  | 265.48   | 239.7           | 179.23
Chicago    | 423.22   | 306.94          | 442.14
Cincinnati | 125      | 202.69          | 175
Cleveland  | 125      | 288.65          | 215.8
Columbus   | 79.25    | 0               | 169.3
Dallas     | 176.48   | 280.72          | 270.06
... (25 rows omitted)