In [3]:
# This will tell Python I want to use the numpy library 
# and I'm going to nickname it np
import numpy as np

from datascience import *

In [5]:
my_array = make_array(1, 2, 3, 4)

In [6]:
my_array

array([1, 2, 3, 4])

In [7]:
type(my_array)

numpy.ndarray

In [8]:
my_array.item(0)

1

In [9]:
my_array.item(1)

2

In [10]:
my_array.item(4)

IndexError: index 4 is out of bounds for axis 0 with size 4

In [11]:
# Bracket notation as shorthand for .item(0)
my_array[0]

1

In [12]:
my_array + 2

array([3, 4, 5, 6])

In [14]:
my_array ** 2

array([ 1,  4,  9, 16])

In [15]:
my_array_2 = make_array(4,5,6,7)

In [16]:
print(my_array)
print(my_array_2)

[1 2 3 4]
[4 5 6 7]

In [17]:
my_array + my_array_2

array([ 5,  7,  9, 11])

In [18]:
my_array_3 = make_array(1,2,3,4,5)

In [19]:
my_array + my_array_3

ValueError: operands could not be broadcast together with shapes (4,) (5,)

In [20]:
sum(my_array)

10

In [21]:
np.average(my_array)

2.5

In [22]:
len(my_array)

4

In [25]:
make_array(0,1,2,3,4,5,6,7,8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
# arange(start, end) starts counting at "start" and goes until "end"
# but does NOT include "end"
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [32]:
# np.arange(start, end, step) and step will specify how much to increment
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [33]:
np.arange(0,1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [34]:
np.arange(20, 0, -2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [ ]:
np.arange(1000)

In [38]:
# This is technically datascience.Table

cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [39]:
cones.show(3)

In [40]:
# How to manually create a table

streets = make_array('Broadway', 'Amsterdam', 'Columbus', 'Manhattan')
streets

array(['Broadway', 'Amsterdam', 'Columbus', 'Manhattan'],
      dtype='<U9')

In [43]:
eastside = Table().with_column('Streets', streets)
eastside

Streets
Broadway
Amsterdam
Columbus
Manhattan

In [50]:
eastside = eastside.with_column('Blocks from campus', np.arange(4))

In [54]:
eastside2 = Table().with_columns('Streets', streets, 'Blocks from campus', np.arange(4))
eastside2

Streets   | Blocks from campus
Broadway  | 0
Amsterdam | 1
Columbus  | 2
Manhattan | 3

In [62]:
cones.select('Flavor').show(2)

In [63]:
cones.show(3)

In [65]:
cones.drop('Price').show(3)

In [67]:
cones.sort('Price', descending=True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
strawberry | pink        | 3.55

In [69]:
# Only give me rows where a condition is met.
# The condition is going to be specified as I give you a column
# And then you take out all the rows in which some predicate is not met
cones.where('Flavor', 'chocolate')

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

In [71]:
# Only give me rows where a condition is met.
# The condition is going to be specified as I give you a column
# And then you take out all the rows in which some predicate is not met
cones.where('Flavor', 'chocolate').drop('Flavor')

Color       | Price
light brown | 4.75
dark brown  | 5.25
dark brown  | 5.25